global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 6.0
   publish_frequency: 4.0
   width: 10.0
   height: 10.0
   resolution: 0.1
   static_map: true
   rolling_window: false
